### ISSUE TITLE
Missing Python module requests had to be installed

### ISSUE THREAD

**Issue by pixolin** [jessedp/pihole5-list-tool#1]
I installed Python3 and pip3 on a Raspberry Pi Zero with Linux distro DietPi. 
Following the instructions on your GitHub page and running `sudo pihole5-list-tool` I got an error message about missing Python module `requests`. After installing that with `sudo pip3 install requests` everything worked like a charm. 
Perhaps you want to add a line to the section [requirements](https://github.com/jessedp/pihole5-list-tool#requirements)?

**Comment by jessedp** [comment]
It's already in there, but I added it to the setup.py install_requires in 0.2.4 (already published) which hopefully will fix that. I'll close this when I get a chance to actually test a that distro or another in that situation or someone else verifies it.
