### ISSUE TITLE
Ask User to automatically enable imported Black-/Whitelists if disabled ?

### ISSUE THREAD

**Issue by MexSalem** [jessedp/pihole5-list-tool#12]
Hi jessedp,

I was able to import new blacklists successfully, but for existing blacklists that I had deactivated in the past, there was no request to activate them. 

I do not recognize which of them are deactivated during import.

Would it be a big programming effort to show the user deactivated blacklists and ask the user if he wants to activate the already existing blacklist if it is deactivated?

```
┌──────────────────────────────────────────┐
│       π-hole 5 list tool  v0.4.3         │
└──────────────────────────────────────────┘
    https://github.com/jessedp/pihole5-list-tool

    Do not hit ENTER or Y if a step seems to hang!
    Use CTRL+C if you're sure it's hung and report it.

docker pihole image not found running, continuing...
? Gravity Db to Update:  /etc/pihole/gravity.db
? Add Blacklists or Whitelists?  Blacklists
? Where are the block lists coming from?  File    | A file with urls of lists, 1 per line
? File to import  /home/neo/RPIList.txt
? Add 90 block lists to /etc/pihole/gravity.db?  Yes
15 block lists added! 75 already existed.

```

**Comment by jessedp** [comment]
I'll have to test to make sure, but "reactivating" should not happen. If a list (and it's existing info like enabled/disabled) exists, this tool doesn't change anything about the record. So if you've marked it disabled, it should stay disabled until you manually change that (or delete and re-add it, but that's not "changing" in this scenario).
