### ISSUE TITLE
Whitelist tool added individual letters as regex whitelists instead of domains

### ISSUE THREAD

**Issue by PaulMorel** [jessedp/pihole5-list-tool#13]
It's a bit hard do explain, so I have this screenshot to convey what I mean.

![image](https://user-images.githubusercontent.com/1200261/83953693-4a6fb780-a810-11ea-8cc3-000ecf8f366f.png)

It seems like the first 9 characters of the first domain on the anudeepND's whitelist were split into separate regex whitelists and the rest, I'm not sure where it comes from.

I doubt this is normal.

Here are my versions:

- Pi-hole v5.0
- AdminLTE  v5.0
- FTL v5.0
- Python v3.7.3
- pip v18.1
- Pi-hole 5 List Tool  v0.4.4

Any ideas?

**Comment by jessedp** [comment]
0.4.5 fixes this.
```
pip3 install pihole5-list-tool --upgrade
```
