### ISSUE TITLE
sqlite3 error

### ISSUE THREAD

**Issue by samascience** [jessedp/pihole5-list-tool#15]
root@Pi-hole:/# pihole5-list-tool
Traceback (most recent call last):
  File "/usr/local/bin/pihole5-list-tool", line 6, in <module>
    from ph5lt import main
  File "/usr/local/lib/python3.7/site-packages/ph5lt.py", line 32, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
root@Pi-hole:/# apt install libsqlite3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libsqlite3-dev is already the newest version (3.16.2-5+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by jessedp** [comment]
I'm guessing you found an article similar to [this in another project](https://github.com/sloria/TextBlob/issues/173#issuecomment-321291279). Installing the dev libraries you have is necessary (as noted there, you may need more), but it looks like you'll also need to rebuild python. 

What OS flavor are you running? I can't imagine why any distro would ship python with out all of the standard libs built in.
