### ISSUE TITLE
script hangs after printing the gravity db to update

### ISSUE THREAD

**Issue by benliepert** [jessedp/pihole5-list-tool#16]
I'm using a Pi 3 Model B with debian version 10.4, pihole5-list-tool version 0.4.5, python 3.7, not using docker.

when I start the script with 'sudo pihole5-list-tool' it gives the following output, and hangs for 10+ minutes. cpu and memory use are .1% and 2.2% respectively, which doesn't seem out of the ordinary to me.

┌──────────────────────────────────────────┐
│       π-hole 5 list tool  v0.4.5                                                              │ └──────────────────────────────────────────┘
    https://github.com/jessedp/pihole5-list-tool

    Do not hit ENTER or Y if a step seems to hang!
    Use CTRL+C if you're sure it's hung and report it.

docker pihole image not found running, continuing...
? Gravity Db to Update:  /etc/pihole/gravity.db

**Comment by jessedp** [comment]
I am only asking this because nothing different from that happens next... did you hit enter there?

**Comment by benliepert** [comment]
that "fixed" it... I took the warning too literally, and it wasn't clear from the demonstration video that input was needed at that step
