### ISSUE TITLE
Downloading AndeepND whitelist basically whitelists everything

### ISSUE THREAD

**Issue by jrnichols** [jessedp/pihole5-list-tool#20]
version 0.4.4 on ubuntu 20.04 LTS

I deleted all of my lists, and only added the AndeepND whitelist, and now I have individual rows where it whitelists individual letters. This basically lets everything through. Oops!

<img width="951" alt="Screen Shot 2020-06-21 at 8 25 15 PM" src="https://user-images.githubusercontent.com/2382525/85245771-7f2d6280-b3fd-11ea-8808-aa6a80c13571.png">

**Comment by jessedp** [comment]
Will you give the current version, 0.5.0, a shot?
```bash
$ pip3 install pihole5-list-tool --upgrade
```

**Comment by jrnichols** [comment]
And now I know how to upgrade the tool as well! :-)

Yes, that resolved it. Thanks! (sorry I didn't check to make sure I had the most current.. my bad!)
