### ISSUE TITLE
pihole5-list tool command error on pi model 4b

### ISSUE THREAD

**Issue by boomi123** [jessedp/pihole5-list-tool#22]
Hi,

Im on a pi model 4b and getting an error if i try to execude the pihole5-list tool command:

Traceback (most recent call last):
  File "/usr/local/bin/pihole5-list-tool", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ph5lt.py", line 84, in main
    print(color("    \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u25
00\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u250
0\u2500\u2500\u2510", fg="#b61042"))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 21-64: ordinal not in range(256)

**Comment by jessedp** [comment]
Check out #4  - you just need to re/configure the language for the OS.
