### ISSUE TITLE
docker not found

### ISSUE THREAD

**Issue by benw525** [jessedp/pihole5-list-tool#23]
Forms suck. But they can help a ton. Going free-form below is okay if you're certain you're providing all of the relevant information (or things aren't applicable)

## Environment
Describe the system on which this issue occurred:

**pihole5-list-tool** v 0.5.0

**OS** v 10

**Python** v 3.8.0

**Using Docker?** Y
.....**version** 19.03.12

## Issue Details
Briefly explain the issue and provide any pertinent stack traces, environment, etc. 

when running command 

> sudo pihole5-list-tool 

I get a message:

> docker not found running, continuing....
> gravity to update: /etc/pihole/gravity.db'

Then nothing else

**Comment by jessedp** [comment]
That's totally possible. The tool is trying to run `docker inspect pihole` and falling back on allowing you to enter the path manually since it can't it.

If that tells you why it can't find your probably running docker image, let me know and I'd be happy to try to update things for future users.
