### ISSUE TITLE
Downgrade list

### ISSUE THREAD

**Issue by ludgats** [jessedp/pihole5-list-tool#28]
Is there any way to change lists? I’m finding too many things are being blocked on I want to move back to the ticked list. When I re run the program it doesn’t remove the old list. Any help is greatly appreciated!

**Comment by jessedp** [comment]
Currently the best you'll be able to do (without using sqlite) is searching for the appropriate List's comment in the web interface and manually disabling/deleting those entries.

**Comment by jessedp** [comment]
v0.6.0 should have a great start at this. Feel free to open new issues for other tweaks/etc to the process.
