### ISSUE TITLE
Removing lists from database

### ISSUE THREAD

**Issue by Ge0rges** [jessedp/pihole5-list-tool#29]
**Is your feature request related to a problem? Please describe.**
Frustrated that when I'm on the command line, I can no longer manage lists of hosts in the gravity databases.

**Describe the solution you'd like**
Add a feature to the tool to delete files same way they were added.

**Describe alternatives you've considered**
Using the web server is not always an option for example when other web servers are already running. And they just complicate stuff.

**Comment by AjkayAlan** [comment]
+1 for this. If I inadvertently select something which is overly permissive, or if I want to "reset" blocklists, I end up manually deleting lists and whitelist entries manually via the UI.

One potential start for the feature - could a "remove all blocklists and whitelists" feature be added? It would be an easy start into this feature and not require any detection on what list gave what entry, etc. It would be a "nuke it all" option.

**Comment by jessedp** [comment]
v0.6.0 should have a great start at this. Feel free to open new issues for other tweaks/etc to the process.
