### ISSUE TITLE
Parsing of Entry on Firebog List

### ISSUE THREAD

**Issue by stevefxp1** [jessedp/pihole5-list-tool#33]
Forms suck. But they can help a ton. Going free-form below is okay if you're certain you're providing all of the relevant information (or things aren't applicable)

## Environment
Describe the system on which this issue occurred:

Version 0.6.0

Ubuntu 20.04.1 LTS

Python 3.8.5

Using Docker? N

## Issue Details
I noticed that your tool is parsing an entry on the Firebog list incorrectly. The entry is https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/TOP_EU_US_Ads_Trackers_HOST but it shows up as https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/TOP_EU_US_Ads_Trackers_HOST in Pi-Hole.

**Comment by jessedp** [comment]
That's not really possible. This tool simply parses lists to make sure entries look like a URL before using them, it doesn't change/modify/rewrite them.

I'd guess that either a previous version of one of the firebog lists used the `github.com` version or you loaded another set of lists that used that.

**Comment by stevefxp1** [comment]
Hi Jesse,

No this is a new Pihole server and I only used your tool to load up the Firebog lists. What I will do is remove all lists and reload.

Steve

⁣
Steven F. Petrillo
stevefxp@gmail.com
Mobile: 1-914-907-2861​
