### ISSUE TITLE
Auto-updating whitelist with this tool? 

### ISSUE THREAD

**Issue by Infinitay** [jessedp/pihole5-list-tool#38]
Previously I used anudeepND's whitelist repo until I stumbled upon this tool and have been using it since. However, I've come to question whether or not updating gravity also updates the whitelist?

When using anudeepND's, he provides a script to update the whitelists, but there's no option to update here. `pihole -g` won't update the whitelist lists, right? So are we intended to re-add the lists with the tool? If so, could you perhaps add a feature to colorize the existing added selected default lists? Would be nice in case down the line we ever forgot which we initially added.

**Comment by jessedp** [comment]
Using this tool, the only way to update lists is to remove and re-add them. There is an option to specifically remove only the lists added through it:
`Manage Blocklists -> Remove Lists Added by This Tool`

`Manage Allowlists -> Remove Lists Added by This Tool`

You may also want to check out [pihole-updatelists](https://github.com/jacklul/pihole-updatelists) which requires a bit more setup, but will keep lists up to date for you.
