### ISSUE TITLE
Error running 0.4.1

### ISSUE THREAD

**Issue by lo97** [jessedp/pihole5-list-tool#7]
Hello,
I tried to install it in lubuntu running pihole 5 but it fails like this
`   ┌──────────────────────────────────────────┐
    │       π-hole 5 list tool  v0.4.1         │
    └──────────────────────────────────────────┘
    https://github.com/jessedp/pihole5-list-tool

    Do not hit ENTER or Y if a step seems to hang!
    Use CTRL+C if you're sure it's hung and report it.

Traceback (most recent call last):
  File "/usr/local/bin/pihole5-list-tool", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ph5lt.py", line 92, in main
    docker = utils.find_docker()
  File "/usr/local/lib/python3.6/dist-packages/utils.py", line 74, in find_docker
    result = subprocess.run(["docker", "inspect", "pihole"], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'`

**Comment by jessedp** [comment]
Would you mind trying 0.4.2?

**Comment by lo97** [comment]
> 
> 
> Would you mind trying 0.4.2?

How?

**Comment by jessedp** [comment]
Install it.
`pip3 install pihole5-list-tool --upgrade`

**Comment by lo97** [comment]
> 
> 
> Install it.
> `pip3 install pihole5-list-tool --upgrade`

Works, thanks
