### ISSUE TITLE
sudo pip3 install pihole5-list-tool --upgrade results in error

### ISSUE THREAD

**Issue by Gizmo-Ger** [jessedp/pihole5-list-tool#8]
I tried to install but the result is the following. Am I missing something?

Collecting pihole5-list-tool
  Using cached https://files.pythonhosted.org/packages/e0/3b/2e8d086b316737a94aca9c787978adee23a79561a6bdeb4965dd5706a50c/pihole5_list_tool-0.4.2-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from pihole5-list-tool) (2.21.0)
Collecting ansicolors (from pihole5-list-tool)
  Using cached https://files.pythonhosted.org/packages/53/18/a56e2fe47b259bb52201093a3a9d4a32014f9d85071ad07e9d60600890ca/ansicolors-1.1.8-py2.py3-none-any.whl
Collecting PyInquirer (from pihole5-list-tool)
  Using cached https://files.pythonhosted.org/packages/fb/4c/434b7c454010a284b49d6f1d446fe8dc5960415613d8c0225b9e2efb6724/PyInquirer-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-mqie3vux/PyInquirer/

**Comment by jessedp** [comment]
You need to install _setuptools_ and that could vary by distribution. Generally speaking, if you [follow the steps in this Requirements section](https://packaging.python.org/tutorials/installing-packages/), you _should_ end up with a fully functioning setup. Then try the pihole5-list-tool install again.

If that doesn't work, search for  ```ModuleNotFoundError: No module named 'setuptools'  <distro>```, replacing distro with what you are using and you should see something useful quickly.
