### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by menace133780** [jessedp/pihole5-list-tool#9]
when I run sudo pihole5-list-tool I get this error:

`Traceback (most recent call last):
  File "/usr/local/bin/pihole5-list-tool", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ph5lt.py", line 82, in main
    print(color('    \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510', fg='#b61042'))
  File "/usr/lib/python3.7/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 21-64: character maps to <undefined>
`

**Comment by jessedp** [comment]
I know it's a different error, but have you tried setting/changing your locale/language options as talk about in #4 ?

**Comment by menace133780** [comment]
Thx for the hint, this solved the problem!
Update worked quite well, nice tool!
